# ShardMatrix 区块链节点配置文件

# 网络配置
network:
  port: 8080
  host: "0.0.0.0"
  bootstrap_peers: []

# 区块链配置
blockchain:
  chain_id: 1
  block_interval: 2  # 区块生成间隔（秒）
  max_block_size: 10485760  # 最大区块大小（10MB）

# 共识配置
consensus:
  type: "pos"  # 共识类型：pos
  validator_count: 21  # 验证者数量
  validators: []  # 验证者地址列表

# 存储配置
storage:
  data_dir: "./data"  # 数据目录
  db_type: "leveldb"  # 数据库类型

# API配置
api:
  port: 8081  # API端口
  host: "127.0.0.1"  # API主机

# 日志配置
log:
  level: "info"  # 日志级别：debug, info, warn, error
  file: ""  # 日志文件路径（空表示输出到控制台）
