# 这是Tendermint的配置文件

# 共识配置
[consensus]
timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "5s"

# P2P配置
[p2p]
laddr = "tcp://0.0.0.0:26656"
seeds = ""
persistent_peers = ""

# RPC配置
[rpc]
laddr = "tcp://0.0.0.0:26657"
cors_allowed_origins = ["*"]
cors_allowed_methods = ["HEAD", "GET", "POST"]
cors_allowed_headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time"]

# 数据库配置
[db]
backend = "goleveldb"
dir = "data" 