# ShardMatrix 生产环境配置
# Production configuration for ShardMatrix node
node:
  node_id: "prod-validator-1"
  data_dir: "/var/lib/shardmatrix"
  log_level: "info"

network:
  listen_addr: ":8546"
  max_peers: 100
  bootstrap_nodes:
    - "bootstrap1.shardmatrix.network:8546"
    - "bootstrap2.shardmatrix.network:8546"
    - "bootstrap3.shardmatrix.network:8546"

api:
  enabled: true
  listen_addr: ":8545"
  cors_origins: ["https://app.shardmatrix.network"]
  rate_limit: 100

consensus:
  type: "dpos"
  is_validator: true
  block_time: "2s"
  genesis_time: 1696521600

storage:
  type: "leveldb"
  cache_size: "512mb"

monitoring:
  enabled: true
  metrics_addr: ":9090"
  health_check_interval: "30s"